In [2]:
import numpy as np
import pandas as pd

1. Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5
matrix. (Score:1)
2. Create a numpy array containing the numbers from 1 to 20, and then extract the
elements between the 5th and 15th index. (Score:1)
3. How to compute the mean, median, and standard deviation of a numpy array?Use the
array you created above (Score 1)
4. Write a NumPy program that creates a 2D array x of shape (3, 4) and a 1D array y of
shape (4,). Subtract y from each row of x using broadcasting. (Score: 2)
5. Create a dataframe with the following columns: name, age, and gender. The dataframe
should have 10 rows of data. (Score: 2)
1) Add a new column to the data frame created in question 1, called occupation.
The values for this column should be Programmer, Manager, and Analyst,
corresponding to the rows in the dataframe. (Score: 1)
2) Select the rows of the dataframe where the age is greater than or equal to 30.
(Score: 1)
3) Convert this dataframe to a CSV file and read that CSV file, and finally display

1. Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5
matrix. (Score:1)

In [5]:
aru= np.arange(1,11).reshape(2,5)
aru

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

2. Create a numpy array containing the numbers from 1 to 20, and then extract the
elements between the 5th and 15th index. (Score:1)

In [13]:
aru=np.arange(1,21)
arr=aru[5:15]
arr

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

3. How to compute the mean, median, and standard deviation of a numpy array?Use the
array you created above (Score 1)

In [72]:
print(aru)
print("Mean=",np.mean(aru))
print("median=",np.median(aru))
print("Standard deviation=",np.std(aru))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Mean= 10.5
median= 10.5
Standard deviation= 5.766281297335398

4. Write a NumPy program that creates a 2D array x of shape (3, 4) and a 1D array y of
shape (4,). Subtract y from each row of x using broadcasting. (Score: 2)

In [66]:
print(f"This is {x.ndim}D array")
x=np.array([[1,2,3,4],[5,6,7,8],[8,3,4,5]])
print(x)

print(f"This is {y.ndim}D array")
y = np.array([2,2,2,2])
print(y)
print("Result")
result= x - y
print(result)

This is 2D array
[[1 2 3 4]
 [5 6 7 8]
 [8 3 4 5]]
This is 1D array
[2 2 2 2]
Result
[[-1  0  1  2]
 [ 3  4  5  6]
 [ 6  1  2  3]]

5. Create a dataframe with the following columns: name, age, and gender. The dataframe
should have 10 rows of data. (Score: 2)

In [67]:
df = pd.DataFrame({
    "name":["pranav","umer","adhil","shone","paraveen","said","jithin","daine","anju","aswathy"],
    "age" :[27,31,24,25,26,24,28,26,28,32],
    "gender":["M","M","M","M","M","M","M","F","F","F"]
})
print(df)

       name  age gender
0    pranav   27      M
1      umer   31      M
2     adhil   24      M
3     shone   25      M
4  paraveen   26      M
5      said   24      M
6    jithin   28      M
7     daine   26      F
8      anju   28      F
9   aswathy   32      F

5.1) Add a new column to the data frame created in question 1, called occupation.
The values for this column should be Programmer, Manager, and Analyst,
corresponding to the rows in the dataframe. (Score: 1)

In [68]:
ddf=[' Programmer',' Manager', 'Analyst,']
df['occupation']=np.resize(ddf,len(df))
df

       name  age gender   occupation
0    pranav   27      M   Programmer
1      umer   31      M      Manager
2     adhil   24      M     Analyst,
3     shone   25      M   Programmer
4  paraveen   26      M      Manager
5      said   24      M     Analyst,
6    jithin   28      M   Programmer
7     daine   26      F      Manager
8      anju   28      F     Analyst,
9   aswathy   32      F   Programmer

5.2) Select the rows of the dataframe where the age is greater than or equal to 30.
(Score: 1)

In [69]:
dft=df[df['age']>=30]
print(dft)

      name  age gender   occupation
1     umer   31      M      Manager
9  aswathy   32      F   Programmer

5.3) Convert this dataframe to a CSV file and read that CSV file, and finally display

In [70]:
df.to_csv("all.csv",index=False)
df_read=pd.read_csv("all.csv")
print(df_read)

       name  age gender   occupation
0    pranav   27      M   Programmer
1      umer   31      M      Manager
2     adhil   24      M     Analyst,
3     shone   25      M   Programmer
4  paraveen   26      M      Manager
5      said   24      M     Analyst,
6    jithin   28      M   Programmer
7     daine   26      F      Manager
8      anju   28      F     Analyst,
9   aswathy   32      F   Programmer

In [71]:
df.reset_index()

   index      name  age gender   occupation
0      0    pranav   27      M   Programmer
1      1      umer   31      M      Manager
2      2     adhil   24      M     Analyst,
3      3     shone   25      M   Programmer
4      4  paraveen   26      M      Manager
5      5      said   24      M     Analyst,
6      6    jithin   28      M   Programmer
7      7     daine   26      F      Manager
8      8      anju   28      F     Analyst,
9      9   aswathy   32      F   Programmer